---
name: build
on:
  push: ~
  pull_request: ~

jobs:
  linux_tests:
    name: PHP ${{ matrix.php }} - ${{ matrix.stability }}
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        php: ['8.1']
        stability: [prefer-lowest, prefer-stable]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          tools: composer:v2

      - name: Check PHP Version
        run: php -v

      - name: Validate composer files
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress ${{ matrix.flags }}

      - name: Run Unit tests with coverage
        run: composer phpunit

      - name: Run PHPStan static analysis
        run: composer phpstan

      - name: Run coding style check
        run: composer phpcs
